### PR TITLE
Simple dots fix

### PR DESCRIPTION
**Pull request by pedantic79**
A simple fix where we sub `...` with `^`, since `^` isn't a valid branch character. This causes us to renumber our arrays. So adjust that `[3]` to `[1]`. Also renamed a variable to `fields`, because it's confusing to use `branch_line` both as an array and not as an array.

### CODE REVIEW

**Comment by davekeane** [comment]
Upstream bug guy here:
This implementation is not working for ahead/behind tracking, though again, haven't looked below this to trace the source.

```
✔ 11:17 user@host ~/s/project [ development-3.2.x | ✔  ] $ ~/src/3rdparty/bash-git-prompt/gitstatus.py
development-3.2.x
↓·3
0
0
0
0
0
1
✔ 11:17 user@host ~/s/project [ development-3.2.x | ✔  ] $ ~/src/3rdparty/bash-git-prompt/gitstatus.sh
development-3.2.x
.
0
0
0
0
0
1
✔ 11:18 user@host ~/s/project [ development-3.2.x | ✔  ] $ 
```

**Comment by pedantic79** [comment]
@davekeane Thanks for catching that. Should be fixed now.

```
✔ /tmp/A [simple-dots-fix ↓·1↑·1|✔]
18:10 $ ~/bash-git-prompt/gitstatus.sh
simple-dots-fix
_BEHIND_1_AHEAD_1
0
0
0
0
0
1

```

**Comment by davekeane** [comment]
Success

```
✔ 13:33 user@host ~/s/project [ development-3.2.x ↓·3 | ✔  ] $ ~/src/3rdparty/bash-git-prompt/gitstatus.py
development-3.2.x
↓·3
0
0
0
0
0
1
✔ 13:33 user@host ~/s/project [ development-3.2.x ↓·3 | ✔  ] $ ~/src/3rdparty/bash-git-prompt/gitstatus.sh
development-3.2.x
_BEHIND_3
0
0
0
0
0
1
✔ 13:33 user@host ~/s/project [ development-3.2.x ↓·3 | ✔  ] $ 
```

**Comment by ogr3** [comment]
This makes minimal changes to the original code, and I like the fields suffix for arrays.

**Pull request merged**
